<digit>			::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<letter>		::= a | b | c | d | e | f | g | h | i | j | k | l | m | n | o | p | q | r | s | t | u | v | w | x | y | z | A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z

<int>			::= [-] <digit> { <digit> }
<float>			::= [-] <digit> { <digit> } '.' <digit> { digit }
<string>		::= " <letter> | <digit> | _ | -  " | ' <letter> | <digit> | _ | -  '
<boolean>		::= 'true' | 'True' | 'false' | 'False'

<object>		::= <int> | <float> | <string> | <boolean>
<variable>		::= <letter> { <letter> | <digit> | _ }

<or_expr>		::= <expr> 'OR' <expr>
<and_expr>		::= <expr> 'AND' <expr>
<bool_expr>		::= <or_expr> | <and_expr>
<arith_expr>	::= <expr> ('+'|'-'|'*'|'/'|'^') <expr>
<comp_expr>		::= <expr> ('=='|'!=') <expr>
<expr>			::= <object> | <variable> | <bool_expr> | <arith_expr> | <comp_expr> | <expr>

<varassign_stmt>::= <variable> = <expr>
<enter_stmt>	::= ('Enter'|'enter') <variable>
<print_stmt>	::= ('Print'|'print') <expr>

<statement>		::= <varassign_stmt> | <enter_stmt> | <print_stmt>
<program>		::= <statement> { \n <statement> }
